"""Engineering-style decision report generator for MatIntel."""

from __future__ import annotations
import numpy as np
import pandas as pd


def _fmt(val, suffix: str = "", fallback: str = "Not available") -> str:
    if val is None or (isinstance(val, float) and np.isnan(val)):
        return fallback
    return f"{val}{suffix}"


def build_report(
    row: pd.Series,
    min_strength: float,
    use_case: str = "Lightweight Structural Component",
    model_metrics: dict | None = None,
) -> str:
    name = row.get("material_name", "Selected material")
    mid = row.get("material_id", "N/A")
    family = row.get("material_family", row.get("family", "N/A"))
    source = row.get("source_dataset", "N/A")
    source_type = row.get("source_type", "N/A")
    trust = _fmt(row.get("source_trust_score"), "/100")

    ys = _fmt(row.get("yield_strength_mpa"), " MPa")
    uts = _fmt(row.get("ultimate_tensile_strength_mpa"), " MPa")
    elong = _fmt(row.get("elongation_percent"), "%")
    density = _fmt(row.get("density_g_cm3"), " g/cm³")
    modulus = _fmt(row.get("youngs_modulus_gpa"), " GPa")
    fatigue = _fmt(row.get("fatigue_strength_mpa"), " MPa")
    corrosion = _fmt(row.get("corrosion_resistance_score"), "/100")

    score = _fmt(row.get("suitability_score"), "/100")
    ws = _fmt(row.get("weight_saving_percent"), "%")
    reasons = row.get("reason_codes", "No reason codes available")

    # Missing data flags
    missing: list[str] = []
    for field, label in [
        ("fatigue_strength_mpa", "Fatigue strength"),
        ("corrosion_resistance_score", "Corrosion resistance"),
        ("hardness_hv", "Hardness"),
        ("thermal_conductivity_w_mk", "Thermal conductivity"),
        ("supplier_risk_score", "Supplier risk assessment"),
    ]:
        val = row.get(field)
        if val is None or (isinstance(val, float) and np.isnan(val)):
            missing.append(f"- **{label}**: not available in source data")

    missing_section = "\n".join(missing) if missing else "- All key fields present."

    # Model info
    model_line = ""
    if model_metrics:
        model_line = (
            f"\n- Model: RandomForest (R² = {model_metrics.get('R2', 'N/A')}, "
            f"MAE = {model_metrics.get('MAE', 'N/A')} MPa, "
            f"trained on {model_metrics.get('train_rows', 'N/A')} experimental rows)"
        )

    # Reason codes formatted as list
    reason_lines = "\n".join(
        f"- {r.strip()}" for r in reasons.split("|") if r.strip()
    )

    return f"""# MatIntel Decision Report

## Use Case
**{use_case}** — Alternative material screening for JLR automotive application.

## Selected Material
| Field | Value |
|-------|-------|
| Material ID | {mid} |
| Material Name | {name} |
| Family | {family} |
| Source Dataset | {source} |
| Source Type | {source_type} |
| Source Trust | {trust} |

## Data Sources Used
- Primary training data: **matminer steel_strength** (312 experimental steel alloys)
- Candidate data source: **{source}** ({source_type}){model_line}

## Known / Predicted Properties
| Property | Value |
|----------|-------|
| Yield Strength | {ys} |
| Ultimate Tensile Strength | {uts} |
| Elongation | {elong} |
| Density | {density} |
| Young's Modulus | {modulus} |
| Fatigue Strength | {fatigue} |
| Corrosion Resistance | {corrosion} |

## Suitability Score
**{score}** (minimum required yield strength: {min_strength} MPa)

Weight saving vs steel baseline: **{ws}**

## Why Recommended
{reason_lines}

## Missing Data / Risk Flags
{missing_section}

> **Note:** Fields marked "demo enrichment" are indicative defaults, not measured values from the source dataset.

## Validation Required
Before engineering release, the following must be completed:
1. **Fatigue testing** — confirm cyclic load performance
2. **Corrosion testing** — salt spray / electrochemical validation
3. **Joining / manufacturing feasibility** — weldability, formability
4. **Crash / impact validation** — dynamic performance under JLR crash spec
5. **Supplier validation** — confirm supply chain, lead time, and certification

## Next Action
Prioritise **{name}** for lab validation and compare against the current steel baseline under the **{use_case}** programme.

---
*Generated by MatIntel — Material Intelligence Platform. Screening only; not final engineering approval.*
"""
